"""Generate the mock PayPal ledger from the current roster so payer_email lines up.

Run with:  python -m the_super.fixtures_gen 2026-09

The scenario is fixed so each of the 5 units demonstrates one state, which makes
it easy to narrate during the demo:
    Unit 1  paid in full on time    -> paid_full
    Unit 2  $400 short              -> underpaid
    Unit 3  nothing found           -> nothing_received
    Unit 4  paid late but in full   -> paid_full (with a date after the due date)
    Unit 5  nothing found, not due  -> not_yet_due
"""

import json
import sys
from datetime import date, timedelta

from .tenants import load_tenants, rent_due_date

FIXTURE = __import__("pathlib").Path(__file__).parent / "fixtures" / "paypal_transactions.json"


def build(month: str, plan: list[str] | None = None) -> dict:
    """plan sets each unit's payment state, in roster order. It is **not random** —
    edit here to change the script.

        full    paid in full on time  -> paid_full
        partial $400 short            -> underpaid
        none    nothing found         -> nothing_received / not_yet_due
        late    paid late but in full -> paid_full (date after the due date)
        recent  paid in full yesterday -> paid_full, and inside the "last few days"
                                    window, used to demonstrate that "I just sent X"
                                    can be verified
    """
    tenants = load_tenants()
    txns = []
    plan = plan or ["recent", "partial", "none", "late", "none"]
    for i, (t, mode) in enumerate(zip(tenants, plan)):
        if mode == "none":
            continue
        due = rent_due_date(t, month)
        amount = t["rent_amount"] if mode != "partial" else t["rent_amount"] - 400
        if mode == "late":
            paid_on = due + timedelta(days=3)
        elif mode == "recent":
            # Yesterday — so find_recent_payments finds it, demonstrating that "I just sent it" verifies
            paid_on = date.today() - timedelta(days=1)
        else:
            paid_on = due
        txns.append({
            "txn_id": f"MOCK-{month[-2:]}{chr(65 + i)}{10 + i}",
            "payer_email": t["email"],
            "amount": round(amount, 2),
            "date": f"{paid_on}T09:00:00-04:00",
            "note": {"full": "paid in full on time", "partial": "short",
                     "late": "paid late but in full", "recent": "sent yesterday"}[mode],
        })
    return {"_comment": f"Generated by fixtures_gen from the roster ({month}). Real emails; do not commit.",
            month: txns}


if __name__ == "__main__":
    month = sys.argv[1] if len(sys.argv) > 1 else "2026-09"
    data = build(month)
    # Last month is in the past and should be fully collected — otherwise the
    # collection logic chases historical arrears, while the demo is about the
    # current month's cycle.
    y, m = (int(x) for x in month.split("-"))
    prev = f"{y-1}-12" if m == 1 else f"{y}-{m-1:02d}"
    data[prev] = build(prev, ["full"] * 5)[prev]
    FIXTURE.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    print(f"✅ Generated {FIXTURE}  ({prev} fully collected + the {month} script)")
